services:
  app:
    image: node:lts
    container_name: front
    tty: true
    volumes:
      - ./:/data
    ports:
      - 5174:5174
    working_dir: /data/front
    command: yarn dev
  redoc:
    image: redocly/redoc
    environment:
      SPEC_URL: api/openapi.yml
    volumes:
      #- ./docs/api/openapi.yml:/usr/share/nginx/html/openapi.yml
      - ./docs/api:/usr/share/nginx/html/api
    ports:
      - 3032:80
