type: object
required:
  - name
properties:
  id:
    type: int
    description: プロジェクトID
    example: 1
    readOnly: true
  name:
    type: string
    description: システム名
    example: project name
    maxLength: 30
  sub_name:
    type: string
    description: サブシステム名
    example: sub project name
    maxLength: 30
  note:
    type: string
    description: システムに関する備考
    example: This is a example note.
    maxLength: 100
    nullable: true
