openapi: "3.1.0"
info:
  title: "Laravel Designer Helper API Documentation"
  version: 1.0.0
  x-logo:
    url: "./api/logo.png"
  description: |
    ## リクエストヘッダ

    | キー         | 値     | 説明             |
    | ------------ | ------ | ---------------- |
    | Accept       | string | application/json |
    | Content-Type | string | application/json |
    | X-NONCE      | string | レスポンス整合性確認用。任意の文字列。 |
    | X-XSRF-TOKEN | string | API認証キー |

    ## レスポンスリソース
    <SchemaDefinition schemaRef="#/components/schemas/ResponseResource" />

    ### ステータスリソース
    <SchemaDefinition schemaRef="#/components/schemas/StatusResource" />

    ## 成功レスポンス
    <SchemaDefinition schemaRef="#/components/schemas/SuccessResource" />

    ### ページネーションメタリソース
    <SchemaDefinition schemaRef="#/components/schemas/MetaResource" />

    ## エラーレスポンス
    <SchemaDefinition schemaRef="#/components/schemas/FailedResource" />

    ### エラーリソース
    <SchemaDefinition schemaRef="#/components/schemas/ErrorResource" />

  license:
    name: MIT
    url: "https://github.com/ikepu-tp/unifestill/blob/a360d012bc517f9c633f3cf034c13e32dc340150/LICENSE"

servers:
  - url: http://localhost/designers
    description: 開発環境サーバ

tags:
  - name: project
    x-displayName: プロジェクト
    description: |
      ## プロジェクトリソース
      <SchemaDefinition schemaRef="#/components/schemas/ProjectResource" />

  - name: table_outline
    x-displayName: テーブル概要
    description: |
      ## テーブル概要リソース
      <SchemaDefinition schemaRef="#/components/schemas/TableOutlineResource" />

  - name: table_detail
    x-displayName: テーブル詳細
    description: |
      ## テーブル詳細リソース
      <SchemaDefinition schemaRef="#/components/schemas/TableDetailResource" />

  - name: table_setting
    x-displayName: テーブル設定
    description: |
      ## テーブル設定リソース
      <SchemaDefinition schemaRef="#/components/schemas/TableSettingResource" />

  - name: function
    x-displayName: 機能
    description: |
      ## 機能リソース
      <SchemaDefinition schemaRef="#/components/schemas/FunctionResource" />

  - name: function_category
    x-displayName: 機能カテゴリー
    description: |
      ## 機能カテゴリーリソース
      <SchemaDefinition schemaRef="#/components/schemas/FunctionCategoryResource" />

  - name: function_class
    x-displayName: 機能区分
    description: |
      ## 機能区分リソース
      <SchemaDefinition schemaRef="#/components/schemas/FunctionClassResource" />

  - name: function_progress
    x-displayName: 機能進捗
    description: |
      ## 機能進捗リソース
      <SchemaDefinition schemaRef="#/components/schemas/FunctionProgressResource" />

  - name: function_user
    x-displayName: 機能ユーザー範囲
    description: |
      ## 機能ユーザー範囲リソース
      <SchemaDefinition schemaRef="#/components/schemas/FunctionUserResource" />

  - name: screen_class
    x-displayName: 画面区分
    description: |
      ## 画面区分リソース
      <SchemaDefinition schemaRef="#/components/schemas/ScreenClassResource" />

  - name: screen_progress
    x-displayName: 画面進捗
    description: |
      ## 画面進捗リソース
      <SchemaDefinition schemaRef="#/components/schemas/ScreenProgressResource" />

  - name: screen
    x-displayName: 画面
    description: |
      ## 画面リソース
      <SchemaDefinition schemaRef="#/components/schemas/ScreenResource" />

  - name: exception
    x-displayName: 例外
    description: |
      ## 例外リソース
      <SchemaDefinition schemaRef="#/components/schemas/ExceptionResource" />

  - name: form_setting
    x-displayName: フォーム設定
    description: |
      ## フォーム設定リソース
      <SchemaDefinition schemaRef="#/components/schemas/FormSettingResource" />

  - name: form
    x-displayName: フォーム
    description: |
      ## フォームリソース
      <SchemaDefinition schemaRef="#/components/schemas/FormResource" />

  - name: form_element
    x-displayName: フォーム要素
    description: |
      ## フォーム要素リソース
      <SchemaDefinition schemaRef="#/components/schemas/FormElementResource" />

x-tagGroups:
  - name: プロジェクト
    tags:
      - project

  - name: テーブル
    tags:
      - table_setting
      - table_outline
      - table_detail

  - name: 機能
    tags:
      - function_category
      - function_class
      - function_progress
      - function_user
      - function

  - name: 画面
    tags:
      - screen
      - screen_class
      - screen_progress

  - name: 例外
    tags:
      - exception

  - name: フォーム
    tags:
      - form_setting
      - form
      - form_element

paths:
  $ref: "./paths/index.yaml"

components:
  parameters:
    $ref: "./components/parameters/index.yaml"
  schemas:
    $ref: "./components/schemas/index.yaml"
  securitySchemes:
    cookieAuth:
      name: "X-XSRF-TOKEN"
      type: "apiKey"
      in: "cookie"
